'use client';
import { useEffect, useRef, useState } from 'react';
import { api } from '@/lib/client/api';
import type { CatalogOptions, ProductDetail } from '@/lib/catalog/service';
const box = 'rounded-xl border border-slate-200 bg-white p-5';
const button = 'rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-600';
const field = 'mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
function Input({ label, value, set, type = 'text', required = false }: { label: string; value: string; set: (v: string) => void; type?: string; required?: boolean }) { return <label className="block text-sm">{label}<input aria-label={label} className={field} type={type} required={required} value={value} onChange={e => set(e.target.value)} /></label>; }
const priceText = (v: ProductDetail['variants'][number]) => v.priceMinor === null ? '' : (v.priceMinor / 10 ** v.currencyScale).toFixed(v.currencyScale);
function VariantForm({ options, submit, initial, busy }: { options: CatalogOptions; submit: (v: Record<string, unknown>) => Promise<void>; initial?: ProductDetail['variants'][number]; busy: boolean }) {
  const [sku,setSku] = useState(''), [name,setName] = useState('Standart'), [price,setPrice] = useState(initial ? priceText(initial) : ''), [stock,setStock] = useState(initial?.stock?.toString() ?? ''), [currency,setCurrency] = useState(initial?.currency ?? 'TRY'), [reason,setReason] = useState(''), [confirmed,setConfirmed] = useState(false);
  return <form className="space-y-3" onSubmit={e => { e.preventDefault(); void submit(initial ? { version: initial.version, price: price || null, stock: stock === '' ? null : Number(stock), reason, confirmed } : { sku, variantName: name, price: price || null, stock: stock === '' ? null : Number(stock), currency, confirmed }); }}>
    <fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2">{!initial && <><Input label="SKU" value={sku} set={setSku} required /><Input label="Varyant adı" value={name} set={setName} required /></>}<Input label="Fiyat (ondalık ayırıcı: nokta; boş: bilinmiyor)" value={price} set={setPrice} /><label className="text-sm">Para birimi<select aria-label="Para birimi" className={field} value={currency} disabled={!!initial} onChange={e => setCurrency(e.target.value)}>{options.currencies.map(c => <option key={c}>{c}</option>)}</select></label><Input label="Stok adedi (boş: bilinmiyor)" value={stock} set={setStock} type="number" />{initial && <Input label="Değişiklik gerekçesi" value={reason} set={setReason} required />}</div><label className="flex items-start gap-2 text-sm"><input type="checkbox" required checked={confirmed} onChange={e => setConfirmed(e.target.checked)} className="mt-1" />Fiyat ve stok bilgilerini kontrol ettim; bu yerel kaydı onaylıyorum.</label><button className={button} disabled={busy}>{busy ? 'Kaydediliyor…' : initial ? 'Fiyat ve stoku kaydet' : 'Varyantı ekle'}</button></fieldset>
  </form>;
}
export function CatalogView({ options }: { options: CatalogOptions }) {
  const [items,setItems] = useState<ProductDetail[]>([]), [total,setTotal] = useState(0), [q,setQ] = useState(''), [brand,setBrand] = useState(''), [status,setStatus] = useState('ACTIVE'), [page,setPage] = useState(1), [refresh,setRefresh] = useState(0);
  const [detail,setDetail] = useState<ProductDetail | null>(null), [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState(''), [creating,setCreating] = useState(false);
  const [newName,setNewName] = useState(''), [description,setDescription] = useState(''), [newBrand,setNewBrand] = useState(options.brands[0]?.id ?? '');
  const [editName,setEditName] = useState(''), [editDescription,setEditDescription] = useState(''); const seq = useRef(0);
  useEffect(() => {
    let cancelled = false; setLoading(true); setDetail(null); ++seq.current;
    const timer = setTimeout(() => { api.get<{ items: ProductDetail[]; total: number }>(`/api/catalog/products?${new URLSearchParams({ q, brand, status, page: String(page) })}`).then(r => { if (!cancelled) { setItems(r.items); setTotal(r.total); setError(''); } }).catch(e => { if (!cancelled) { setItems([]); setError(e.message); } }).finally(() => { if (!cancelled) setLoading(false); }); }, 200);
    return () => { cancelled = true; ++seq.current; clearTimeout(timer); };
  }, [q,brand,status,page,refresh]);
  async function open(id: string) { const n = ++seq.current; setError(''); setDetail(null); try { const d = await api.get<ProductDetail>(`/api/catalog/products/${id}`); if (seq.current === n) { setDetail(d); setEditName(d.name); setEditDescription(d.description); } } catch(e) { if (n === seq.current) setError(e instanceof Error ? e.message : 'Kayıt açılamadı.'); } }
  async function mutate(run: () => Promise<unknown>) { setBusy(true); setError(''); setNotice(''); try { await run(); setCreating(false); setDetail(null); setRefresh(v => v + 1); setNotice('Katalog kaydı kaydedildi. Harici mağazaya veya reklam ağına işlem gönderilmedi.'); } catch(e) { setError(e instanceof Error ? e.message : 'Kayıt başarısız.'); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Ürün Kataloğu</h1><p className="mt-2 text-sm text-slate-600">Markalarınızın merkezi ürün, varyant, fiyat ve stok kayıtları.</p></div>{options.canWrite && <button className={button} disabled={busy || !options.brands.length} onClick={() => { setCreating(v => !v); setDetail(null); ++seq.current; }}>Yeni ürün</button>}</header>
    <p className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">Bilgiler kullanıcı tarafından girilir; canlı mağaza veya sağlayıcı senkronizasyonu değildir. Bilinmeyen fiyat/stok boş bırakılır. Arşivleme geçmiş kayıtları silmez. {options.brands.length === 0 && 'Başlamak için Marka Profilleri bölümünde bir marka oluşturun.'}</p>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
    {creating && <section className={`${box} space-y-4`}><h2 className="font-semibold">Ürün ve ilk varyant</h2><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><Input label="Ürün adı" value={newName} set={setNewName} required /><label className="text-sm">Ürün markası<select aria-label="Ürün markası" className={field} value={newBrand} onChange={e => setNewBrand(e.target.value)}>{options.brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Input label="Ürün açıklaması" value={description} set={setDescription} /></fieldset><VariantForm options={options} busy={busy} submit={v => mutate(() => api.post('/api/catalog/products', { ...v, brandId: newBrand, name: newName, description }))} /><button className={button} disabled={busy} onClick={() => setCreating(false)}>Vazgeç</button></section>}
    <section className={box}><fieldset disabled={busy} className="grid items-end gap-3 sm:grid-cols-4"><Input label="Ürün adı veya SKU ara" value={q} set={v => { setQ(v); setPage(1); }} /><label className="text-sm">Marka<select aria-label="Marka" className={field} value={brand} onChange={e => { setBrand(e.target.value); setPage(1); }}><option value="">Tüm markalar</option>{options.brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-sm">Durum<select aria-label="Durum" className={field} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="ACTIVE">Aktif</option><option value="ARCHIVED">Arşivlenmiş</option><option value="ALL">Tümü</option></select></label><button className={button} disabled={loading} onClick={() => setRefresh(v => v + 1)}>Yenile</button></fieldset></section>
    <section aria-label="Ürün listesi" aria-busy={loading} className="space-y-3">{loading ? <p role="status">Ürünler yükleniyor…</p> : !error && !items.length ? <p className={`${box} py-10 text-center text-slate-500`}>Bu filtrede ürün bulunamadı. Örnek ürün eklenmedi.</p> : items.map(p => <article key={p.id} className={`${box} flex flex-wrap items-center justify-between gap-3`}><div><h2 className="font-semibold">{p.name}</h2><p className="mt-1 text-sm text-slate-500">{p.brand.name} · {p.variants.length} varyant · {p.status === 'ACTIVE' ? 'Aktif' : 'Arşivlenmiş'}</p></div><button className={button} disabled={busy} onClick={() => { setCreating(false); void open(p.id); }}>Ürünü incele</button></article>)}</section>
    {!loading && !error && total > 0 && <div className="flex items-center justify-between gap-2"><button className={button} disabled={busy || page <= 1} onClick={() => setPage(v => v - 1)}>Önceki</button><span className="text-sm">{total} ürün · Sayfa {page} / {Math.ceil(total / 20)}</span><button className={button} disabled={busy || page * 20 >= total} onClick={() => setPage(v => v + 1)}>Sonraki</button></div>}
    {detail && <section className={`${box} space-y-5`}><div className="flex justify-between gap-2"><h2 className="font-semibold">{detail.name} · Ürün ayrıntıları</h2><button className={button} disabled={busy} onClick={() => setDetail(null)}>Kapat</button></div>{options.canWrite ? <form className="space-y-3" onSubmit={e => { e.preventDefault(); void mutate(() => api.patch(`/api/catalog/products/${detail.id}`, { name: editName, description: editDescription, status: detail.status, version: detail.version })); }}><fieldset disabled={busy} className="space-y-3"><Input label="Ürün adını düzenle" value={editName} set={setEditName} required /><Input label="Açıklamayı düzenle" value={editDescription} set={setEditDescription} /><button className={button}>Ürün bilgilerini kaydet</button><button type="button" className={`${button} ml-2`} onClick={() => { if (confirm(detail.status === 'ACTIVE' ? 'Ürün arşivlensin mi? Geçmiş korunur, ürün yanıt kaynağı olarak kullanılamaz.' : 'Ürün yeniden etkinleştirilsin mi?')) void mutate(() => api.patch(`/api/catalog/products/${detail.id}`, { name: detail.name, description: detail.description, status: detail.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE', version: detail.version })); }}>{detail.status === 'ACTIVE' ? 'Arşivle' : 'Yeniden etkinleştir'}</button></fieldset></form> : <p className="text-sm">{detail.description || 'Açıklama yok.'}</p>}
      {detail.variants.map(v => <article key={`${v.id}:${v.version}`} className="space-y-3 rounded-lg border border-slate-200 p-4"><h3 className="break-words font-medium">{v.name} · {v.sku}</h3><p className="text-sm">Fiyat: {v.priceMinor === null ? 'Bilinmiyor' : `${priceText(v)} ${v.currency}`} · Stok: {v.stock ?? 'Bilinmiyor'}</p><p className="text-xs text-slate-500">Kaynak: kullanıcı beyanı · Son doğrulama: {v.verifiedAt ? new Date(v.verifiedAt).toLocaleString('tr-TR') : 'Yok'}</p>{options.canWrite && detail.status === 'ACTIVE' && <details><summary className="cursor-pointer text-sm text-violet-700">Fiyat ve stok güncelle</summary><div className="mt-3"><VariantForm initial={v} options={options} busy={busy} submit={input => mutate(() => api.patch(`/api/catalog/variants/${v.id}`, input))} /></div></details>}<details><summary className="cursor-pointer text-sm">Stok geçmişi · Son 20 kayıt</summary><ul className="mt-2 space-y-2 text-sm">{v.inventory.length === 0 && <li>Stok henüz bildirilmedi.</li>}{v.inventory.map(m => <li key={m.id}>{m.fromStock ?? 'Bilinmiyor'} → {m.toStock} · {m.reason} · {new Date(m.createdAt).toLocaleString('tr-TR')}</li>)}</ul></details></article>)}
      {options.canWrite && detail.status === 'ACTIVE' && detail.variants.length < 50 && <details key={`${detail.id}:${detail.version}`}><summary className="cursor-pointer font-medium">Yeni varyant ekle</summary><div className="mt-3"><VariantForm options={options} busy={busy} submit={v => mutate(() => api.post(`/api/catalog/products/${detail.id}/variants`, { ...v, version: detail.version }))} /></div></details>}
    </section>}
  </div>;
}
