'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { api } from '@/lib/client/api';
import type { ContactDetail, ContactList, CrmOptions } from '@/lib/crm/service';
const box='rounded-xl border border-slate-200 bg-white p-5';
const button='rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-600';
const field='mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
const stages:Record<string,string>={NEW:'Yeni',QUALIFIED:'Nitelikli',PROPOSAL:'Teklif',WON:'Kazanıldı',LOST:'Kaybedildi'};
function Input({label,value,set,type='text',required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm">{label}<input aria-label={label} className={field} value={value} type={type} required={required} onChange={e=>set(e.target.value)}/></label>;}
function Select({label,value,set,items,empty='Seçilmedi'}:{label:string;value:string;set:(v:string)=>void;items:{id:string;name:string}[];empty?:string|null}){return <label className="block text-sm">{label}<select aria-label={label} className={field} value={value} onChange={e=>set(e.target.value)}>{empty!==null&&<option value="">{empty}</option>}{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>;}
function LeadEditor({options,lead,busy,submit}:{options:CrmOptions;lead?:ContactDetail['leads'][number];busy:boolean;submit:(v:Record<string,unknown>)=>Promise<void>}){
 const [title,setTitle]=useState(lead?.title??''),[owner,setOwner]=useState(lead?.ownerId??''),[campaign,setCampaign]=useState(lead?.campaignId??''),[stage,setStage]=useState(lead?.stage??'NEW'),[reason,setReason]=useState('');
 return <form onSubmit={e=>{e.preventDefault();void submit({title,ownerId:owner||null,campaignId:campaign||null,...(lead?{version:lead.version,stage,reason}:{})});}}><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input label="Fırsat başlığı" value={title} set={setTitle} required/><Select label="Sorumlu" value={owner} set={setOwner} items={options.users}/><Select label="Mevcut kampanya" value={campaign} set={setCampaign} items={options.campaigns}/>{lead&&<Select label="Satış aşaması" value={stage} set={setStage} empty={null} items={Object.entries(stages).map(([id,name])=>({id,name}))}/>}</div>{lead&&<Input label="Değişiklik gerekçesi" value={reason} set={setReason} required/>}<button className={button}>{busy?'Kaydediliyor…':lead?'Fırsatı güncelle':'Fırsat oluştur'}</button></fieldset></form>;
}
function LeadCard({lead,options,editable,busy,mutate}:{lead:ContactDetail['leads'][number];options:CrmOptions;editable:boolean;busy:boolean;mutate:(f:()=>Promise<unknown>)=>Promise<void>}){
 const [note,setNote]=useState('');
 return <article className="space-y-3 rounded-lg border border-slate-200 p-4"><h3 className="font-semibold">{lead.title} · {stages[lead.stage]??'Bilinmiyor'}</h3><p className="text-sm text-slate-500">Sorumlu: {lead.owner?.name??'Atanmadı'} · Kampanya: {lead.campaign?.name??'Bağlanmadı'}</p>{editable&&<details><summary className="cursor-pointer text-sm text-violet-700">Fırsatı düzenle</summary><div className="mt-3"><LeadEditor lead={lead} options={options} busy={busy} submit={v=>mutate(()=>api.patch(`/api/crm/leads/${lead.id}`,v))}/></div></details>}
 <details><summary className="cursor-pointer text-sm">İç notlar ve geçmiş · Son 30 kayıt</summary><ul className="mt-3 space-y-2 text-sm">{lead.activities.map(a=><li key={a.id} className="rounded-lg bg-slate-50 p-3"><strong>{a.type==='INTERNAL_NOTE'?'İç not':'İşlem kaydı'}</strong> · {new Date(a.createdAt).toLocaleString('tr-TR')}<p className="mt-1 whitespace-pre-wrap break-words">{a.text}</p></li>)}</ul></details>
 {editable&&<form onSubmit={e=>{e.preventDefault();void mutate(()=>api.post(`/api/crm/leads/${lead.id}/notes`,{text:note}));}}><fieldset disabled={busy} className="space-y-2"><Input label="Yalnızca ekip içi not" value={note} set={setNote} required/><p className="text-xs text-slate-500">Müşteriye veya sosyal ağa gönderilmez. Gereksiz hassas kişisel bilgi eklemeyin.</p><button className={button}>İç not ekle</button></fieldset></form>}</article>;
}
export function CrmView({options}:{options:CrmOptions}){
 const [data,setData]=useState<ContactList>({items:[],total:0,page:1}),[q,setQ]=useState(''),[brand,setBrand]=useState(''),[status,setStatus]=useState('ACTIVE'),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[detail,setDetail]=useState<ContactDetail|null>(null),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[newBrand,setNewBrand]=useState(options.brands[0]?.id??''),[confirmed,setConfirmed]=useState(false),[conversation,setConversation]=useState('');const seq=useRef(0);
 useEffect(()=>{let cancelled=false;setLoading(true);setDetail(null);++seq.current;const timer=setTimeout(()=>{api.get<ContactList>(`/api/crm/contacts?${new URLSearchParams({q,brand,status,page:String(page)})}`).then(r=>{if(!cancelled){setData(r);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});},200);return()=>{cancelled=true;++seq.current;clearTimeout(timer);};},[q,brand,status,page,refresh]);
 async function open(id:string){const n=++seq.current;setDetail(null);setCreating(false);setError('');try{const c=await api.get<ContactDetail>(`/api/crm/contacts/${id}`);if(n===seq.current){setDetail(c);setName(c.name);setEmail(c.email??'');setPhone(c.phone??'');setConversation('');}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Kayıt açılamadı.');}}
 async function mutate(run:()=>Promise<unknown>,keep=true){setBusy(true);setError('');setNotice('');try{await run();setCreating(false);if(keep&&detail)await open(detail.id);else{setDetail(null);setRefresh(v=>v+1);}setNotice('CRM kaydı kaydedildi. Dış mesaj gönderilmedi; gelir kaydı oluşturulmadı.');}catch(e){setError(e instanceof Error?e.message:'İşlem başarısız.');}finally{setBusy(false);}}
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('contact');if(id)void open(id);},[]);
 const editable=options.canWrite&&detail?.status==='ACTIVE';
 return <div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Müşteriler ve Fırsatlar</h1><p className="mt-2 text-sm text-slate-600">Kişiler, satış aşamaları ve mevcut Gelen Kutusu bağlantıları.</p></div>{options.canWrite&&<button className={button} disabled={busy||!options.brands.length} onClick={()=>{++seq.current;setDetail(null);setCreating(v=>!v);setName('');setEmail('');setPhone('');setConfirmed(false);}}>Yeni kişi</button>}</header>
 <p className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">Yalnızca hukuki dayanağınız olan gerekli iletişim bilgilerini kaydedin. Aynı isim/e-posta otomatik birleştirilmez. “Kazanıldı” satış aşamasıdır; tahsilat veya doğrulanmış gelir değildir. {options.brands.length===0&&'Önce bir marka oluşturun.'}</p>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
 {creating&&<section className={box}><h2 className="mb-3 font-semibold">Yeni kişi kaydı</h2><form onSubmit={e=>{e.preventDefault();void mutate(()=>api.post('/api/crm/contacts',{name,email:email||null,phone:phone||null,brandId:newBrand,lawfulBasisConfirmed:confirmed}),false);}}><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input label="Kişi adı" value={name} set={setName} required/><Select label="Kişi markası" value={newBrand} set={setNewBrand} items={options.brands} empty={null}/><Input label="E-posta (isteğe bağlı)" value={email} set={setEmail} type="email"/><Input label="Telefon (isteğe bağlı)" value={phone} set={setPhone} type="tel"/></div><label className="flex items-start gap-2 text-sm"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Bu kişisel veriyi kaydetmek için hukuki dayanağım var.</label><button className={button}>Kişiyi kaydet</button><button type="button" className={`${button} ml-2`} onClick={()=>setCreating(false)}>Vazgeç</button></fieldset></form></section>}
 <section className={box}><fieldset disabled={busy} className="grid items-end gap-3 sm:grid-cols-4"><Input label="Kişi adı veya e-posta ara" value={q} set={v=>{setQ(v);setPage(1);}}/><Select label="Marka filtresi" value={brand} set={v=>{setBrand(v);setPage(1);}} items={options.brands} empty="Tüm markalar"/><Select label="Kişi durumu" value={status} set={v=>{setStatus(v);setPage(1);}} empty={null} items={[{id:'ACTIVE',name:'Aktif'},{id:'ARCHIVED',name:'Arşivlenmiş'}]}/><button className={button} disabled={loading} onClick={()=>setRefresh(v=>v+1)}>Listeyi yenile</button></fieldset></section>
 <section aria-label="Kişi listesi" aria-busy={loading} className="space-y-3">{loading?<p role="status">Kişiler yükleniyor…</p>:!error&&!data.items.length?<p className={`${box} py-10 text-center text-slate-500`}>Bu filtrede kişi bulunamadı. Örnek müşteri eklenmedi.</p>:!error&&data.items.map(c=><article key={c.id} className={`${box} flex flex-wrap items-center justify-between gap-3`}><div><h2 className="font-semibold">{c.name}</h2><p className="mt-1 break-all text-sm text-slate-500">{c.brand.name} · {c.email??'E-posta yok'} · {options.leadsEnabled?`${c._count.leads} fırsat · `:''}{c._count.conversations} konuşma</p></div><button className={button} disabled={busy} onClick={()=>void open(c.id)}>Kişiyi incele</button></article>)}</section>
 {!loading&&!error&&data.total>0&&<div className="flex items-center justify-between gap-2"><button className={button} disabled={busy||page<=1} onClick={()=>setPage(v=>v-1)}>Önceki</button><span className="text-sm">{data.total} kişi · Sayfa {page} / {Math.ceil(data.total/20)}</span><button className={button} disabled={busy||page*20>=data.total} onClick={()=>setPage(v=>v+1)}>Sonraki</button></div>}
 {detail&&<section className={`${box} space-y-5`}><div className="flex justify-between gap-2"><h2 className="font-semibold">{detail.name} · Kişi ayrıntıları</h2><button className={button} disabled={busy} onClick={()=>setDetail(null)}>Kapat</button></div><p className="text-xs text-slate-500">Kaynak: kullanıcı beyanı · {detail.brand.name}. Arşivleme kişisel veri silme işlemi değildir.</p>{options.canWrite?<form onSubmit={e=>{e.preventDefault();void mutate(()=>api.patch(`/api/crm/contacts/${detail.id}`,{name,email:email||null,phone:phone||null,status:detail.status,version:detail.version}),false);}}><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Input label="Kişi adını düzenle" value={name} set={setName} required/><Input label="E-postayı düzenle" value={email} set={setEmail} type="email"/><Input label="Telefonu düzenle" value={phone} set={setPhone} type="tel"/></div><button className={button}>Kişiyi güncelle</button><button type="button" className={`${button} ml-2`} onClick={()=>{if(confirm(detail.status==='ACTIVE'?'Kişi arşivlensin mi? İletişim bilgileri ve geçmiş silinmez.':'Kişi yeniden etkinleştirilsin mi?'))void mutate(()=>api.patch(`/api/crm/contacts/${detail.id}`,{name:detail.name,email:detail.email,phone:detail.phone,status:detail.status==='ACTIVE'?'ARCHIVED':'ACTIVE',version:detail.version}),false);}}>{detail.status==='ACTIVE'?'Kişiyi arşivle':'Yeniden etkinleştir'}</button></fieldset></form>:<p className="break-all text-sm">{detail.email??'E-posta yok'} · {detail.phone??'Telefon yok'}</p>}
 <div className="space-y-3"><h3 className="font-semibold">Gelen Kutusu bağlantıları</h3>{detail.conversations.length===0&&<p className="text-sm text-slate-500">Bağlı konuşma yok.</p>}{detail.conversations.map(c=><div key={c.id} className="flex flex-wrap items-center gap-3"><Link className="text-sm text-violet-700 underline" href={`/app/gelen-kutusu?conversation=${encodeURIComponent(c.conversationId)}`}>{c.conversation.provider} konuşmasını aç</Link>{options.canWrite&&<button className={button} disabled={busy} onClick={()=>void mutate(()=>api.post(`/api/crm/contacts/${detail.id}/conversations/unlink`,{conversationId:c.conversationId,version:detail.version}))}>Eşleştirmeyi kaldır</button>}</div>)}{editable&&<form onSubmit={e=>{e.preventDefault();void mutate(()=>api.post(`/api/crm/contacts/${detail.id}/conversations`,{conversationId:conversation,version:detail.version}));}}><fieldset disabled={busy} className="space-y-2"><Select label="Aynı markanın konuşması" value={conversation} set={setConversation} items={options.conversations.filter(c=>c.brandId===detail.brandId&&!detail.conversations.some(l=>l.conversationId===c.id)).map(c=>({id:c.id,name:`${c.participant.displayName} · ${c.provider}`}))}/><p className="text-xs text-slate-500">En son 100 bağlanmamış konuşma arasından seçilir. Kimliği manuel doğrulayın; mesajlar değiştirilmez.</p><button className={button} disabled={!conversation}>Konuşmayı eşleştir</button></fieldset></form>}</div>
 {options.leadsEnabled&&<div className="space-y-4"><h3 className="font-semibold">Satış fırsatları</h3>{detail.leads.length===0&&<p className="text-sm text-slate-500">Henüz fırsat yok.</p>}{detail.leads.map(l=><LeadCard key={`${l.id}:${l.version}:${l.activities.length}`} lead={l} options={options} editable={!!editable} busy={busy} mutate={mutate}/>)}{editable&&detail.leads.length<100&&<details key={`${detail.id}:${detail.leads.length}`}><summary className="cursor-pointer text-sm font-semibold text-violet-700">Yeni fırsat ekle</summary><div className="mt-3"><LeadEditor options={options} busy={busy} submit={v=>mutate(()=>api.post(`/api/crm/contacts/${detail.id}/leads`,v))}/></div></details>}</div>}
 </section>}
 </div>;
}
