import {after,before,it} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import prisma from '../src/lib/prisma';
import type {SessionContext} from '../src/lib/auth/session';
import {BusinessError} from '../src/lib/business/access';
import {createContact,getContact,listContacts,updateContact,linkConversation,unlinkConversation,createLead,updateLead,addLeadNote} from '../src/lib/crm/service';
if(!process.env.DATABASE_URL?.endsWith('test.db'))throw Error('Ayrı test DB gerekli.');
let a:SessionContext,b:SessionContext,viewer:SessionContext,brand:string,otherBrand:string,campaign:string,foreignCampaign:string,id:string,leadId:string,conversation:string,wrongBrandConversation:string;
const workspaces:string[]=[];const code=(c:string)=>(e:unknown)=>e instanceof BusinessError&&e.code===c;
async function fixture(){const w=await prisma.workspace.create({data:{name:'CRM test',slug:randomUUID()}});workspaces.push(w.id);const u=await prisma.user.create({data:{workspaceId:w.id,email:`${randomUUID()}@test.invalid`,passwordHash:'no-login',name:'CRM',role:'OWNER'}});return{sessionId:'test',csrfToken:'test',user:{...u,role:'OWNER',workspaceName:w.name,workspaceSlug:w.slug,demoMode:true}}as SessionContext;}
async function conv(brandId:string){const workspaceId=a.user.workspaceId;const account=await prisma.socialAccount.create({data:{workspaceId,brandId,platform:'INSTAGRAM',handle:`@test-${randomUUID()}`,displayName:'Test'}});const p=await prisma.socialParticipant.create({data:{workspaceId,socialAccountId:account.id,providerParticipantId:randomUUID(),displayName:'Test kişi'}});return(await prisma.socialConversation.create({data:{workspaceId,brandId,socialAccountId:account.id,participantId:p.id,provider:'INSTAGRAM',providerConversationId:randomUUID(),type:'COMMENT'}})).id;}
before(async()=>{a=await fixture();b=await fixture();brand=(await prisma.brand.create({data:{workspaceId:a.user.workspaceId,name:'A',slug:'a'}})).id;otherBrand=(await prisma.brand.create({data:{workspaceId:a.user.workspaceId,name:'B',slug:'b'}})).id;campaign=(await prisma.campaign.create({data:{workspaceId:a.user.workspaceId,name:'Mevcut kampanya',code:'a'}})).id;foreignCampaign=(await prisma.campaign.create({data:{workspaceId:b.user.workspaceId,name:'Başka tenant',code:'b'}})).id;const v=await prisma.user.create({data:{workspaceId:a.user.workspaceId,email:`${randomUUID()}@test.invalid`,name:'Viewer',passwordHash:'no-login',role:'VIEWER'}});viewer={...a,user:{...a.user,id:v.id,role:'VIEWER'}};conversation=await conv(brand);wrongBrandConversation=await conv(otherBrand);id=(await createContact(a,{brandId:brand,name:'Kullanıcı beyanı',email:'PERSON@example.invalid',phone:null,lawfulBasisConfirmed:true})).id;});
after(async()=>{for(const workspaceId of workspaces){await prisma.contactConversationLink.deleteMany({where:{workspaceId}});await prisma.leadActivity.deleteMany({where:{workspaceId}});await prisma.lead.deleteMany({where:{workspaceId}});await prisma.contact.deleteMany({where:{workspaceId}});await prisma.socialConversation.deleteMany({where:{workspaceId}});await prisma.socialParticipant.deleteMany({where:{workspaceId}});await prisma.workspace.delete({where:{id:workspaceId}});}await prisma.$disconnect();});
it('kişi kaydı kullanıcı beyanı, kişisel bilgi audit metadatasına kopyalanmaz',async()=>{const c=await getContact(a,id);assert.equal(c.source,'USER_PROVIDED');assert.equal(c.email,'person@example.invalid');const logs=await prisma.auditLog.findMany({where:{entityId:id}});assert.ok(!JSON.stringify(logs).includes('person@example.invalid'));});
it('tenant kapsamı ve sahte rol yükseltme reddedilir',async()=>{await assert.rejects(getContact(b,id),code('NOT_FOUND'));assert.equal((await listContacts(b)).total,0);await assert.rejects(updateContact({...viewer,user:{...viewer.user,role:'OWNER'}},id,{name:'x',email:null,phone:null,status:'ACTIVE',version:1}),code('FORBIDDEN'));});
it('hukuki dayanak onayı ve alan doğrulaması zorunlu',async()=>{await assert.rejects(createContact(a,{brandId:brand,name:'x',lawfulBasisConfirmed:false}),code('CONFIRMATION_REQUIRED'));await assert.rejects(createContact(a,{brandId:brand,name:'x',email:'invalid',lawfulBasisConfirmed:true}),code('INVALID_INPUT'));await assert.rejects(createContact(a,{brandId:brand,name:'x',workspaceId:b.user.workspaceId,lawfulBasisConfirmed:true}),code('INVALID_INPUT'));});
it('aynı görünen kişi otomatik birleştirilmez',async()=>{const x=await createContact(a,{brandId:brand,name:'Kullanıcı beyanı',email:'person@example.invalid',phone:null,lawfulBasisConfirmed:true});assert.notEqual(x.id,id);});
it('konuşma aynı tenant ve marka olmalı; tek kişiye bağlanır ve sürümlüdür',async()=>{await assert.rejects(linkConversation(a,id,{conversationId:wrongBrandConversation,version:1}),code('NOT_FOUND'));await linkConversation(a,id,{conversationId:conversation,version:1});const c=await getContact(a,id);assert.equal(c.conversations.length,1);assert.equal(c.version,2);await assert.rejects(linkConversation(a,id,{conversationId:conversation,version:1}),code('CONFLICT'));await assert.rejects(linkConversation(a,id,{conversationId:conversation,version:2}));assert.equal((await getContact(a,id)).version,2);});
it('hatalı eşleştirme geri alınabilir; konuşma/mesaj silinmez',async()=>{await unlinkConversation(a,id,{conversationId:conversation,version:2});assert.equal((await getContact(a,id)).conversations.length,0);assert.ok(await prisma.socialConversation.findUnique({where:{id:conversation}}));});
it('Lead mevcut Campaign ve User referanslarını kullanır; tenant dışı sahip/kampanya reddi',async()=>{await assert.rejects(createLead(a,id,{title:'Teklif',ownerId:b.user.id,campaignId:null}),code('NOT_FOUND'));await assert.rejects(createLead(a,id,{title:'Teklif',ownerId:null,campaignId:foreignCampaign}),code('NOT_FOUND'));leadId=(await createLead(a,id,{title:'Teklif',ownerId:a.user.id,campaignId:campaign})).id;const l=(await getContact(a,id)).leads[0];assert.equal(l.campaignId,campaign);assert.equal(l.stage,'NEW');assert.equal(l.activities[0].type,'CREATED');});
it('aşama değişikliği audit+aktiviteyle atomik; WON gelir veya yayın üretmez',async()=>{const jobs=await prisma.job.count(),analytics=await prisma.analyticsSnapshot.count();const body={title:'Teklif',stage:'WON',ownerId:a.user.id,campaignId:campaign,version:1,reason:'Kullanıcı manuel kararı'};await updateLead(a,leadId,body);await assert.rejects(updateLead(a,leadId,body),code('CONFLICT'));assert.equal((await getContact(a,id)).leads[0].stage,'WON');assert.equal(await prisma.job.count(),jobs);assert.equal(await prisma.analyticsSnapshot.count(),analytics);});
it('iç not hiçbir dış mesaj/Job oluşturmaz; tenant dışı nota erişim yok',async()=>{const messages=await prisma.socialMessage.count(),jobs=await prisma.job.count();await addLeadNote(a,leadId,{text:'Sadece ekip içi değerlendirme'});assert.equal(await prisma.socialMessage.count(),messages);assert.equal(await prisma.job.count(),jobs);assert.ok((await getContact(a,id)).leads[0].activities.some(a=>a.type==='INTERNAL_NOTE'));await assert.rejects(addLeadNote(b,leadId,{text:'Yetkisiz'}),code('NOT_FOUND'));});
it('arşivleme geçmişi korur ve yeni Lead/nota engel olur',async()=>{const c=await getContact(a,id);await updateContact(a,id,{name:c.name,email:c.email,phone:c.phone,status:'ARCHIVED',version:c.version});assert.equal((await getContact(a,id)).leads.length,1);await assert.rejects(createLead(a,id,{title:'Yeni',ownerId:null,campaignId:null}),code('ARCHIVED'));await assert.rejects(addLeadNote(a,leadId,{text:'Yeni'}),code('ARCHIVED'));});
it('özellik bayrakları gerçek servis kapılarıdır',async()=>{const old=process.env.FF_SOCIAL_CRM;process.env.FF_SOCIAL_CRM='false';try{await assert.rejects(getContact(a,id),code('FEATURE_DISABLED'));}finally{if(old===undefined)delete process.env.FF_SOCIAL_CRM;else process.env.FF_SOCIAL_CRM=old;}const oldLead=process.env.FF_LEAD_MANAGEMENT;process.env.FF_LEAD_MANAGEMENT='false';try{assert.deepEqual((await getContact(a,id)).leads,[]);await assert.rejects(addLeadNote(a,leadId,{text:'x'}),code('FEATURE_DISABLED'));}finally{if(oldLead===undefined)delete process.env.FF_LEAD_MANAGEMENT;else process.env.FF_LEAD_MANAGEMENT=oldLead;}});
it('composite FK çapraz workspace Lead ilişkisini DB seviyesinde engeller',async()=>{await assert.rejects(prisma.lead.create({data:{workspaceId:b.user.workspaceId,contactId:id,title:'cross'}}));});
